apiVersion: v1
kind: Service
metadata:
  name: sentiment-model
  namespace: sentiment-analysis
  labels:
    app: sentiment-model
spec:
  type: LoadBalancer
  selector:
    app: sentiment-model
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
